<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");

if(!((isset($_REQUEST["ELEMENT_CODE"])
        && !empty($_REQUEST["ELEMENT_CODE"]))
    || (isset($_REQUEST["ELEMENT_ID"])
        && !empty($_REQUEST["ELEMENT_ID"])))){
    LocalRedirect('/amp/');
}

?><?$APPLICATION->IncludeComponent(
    "bitrix:catalog.element",
    "ampproduct",
    Array(
        "NOT_MUCH" => 5,
        "ACTION_VARIABLE" => "action",
        "ADD_DETAIL_TO_SLIDER" => "N",
        "ADD_ELEMENT_CHAIN" => "N",
        "ADD_PICT_PROP" => "-",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "ADD_TO_BASKET_ACTION" => array("BUY"),
        "ADD_TO_BASKET_ACTION_PRIMARY" => array("BUY"),
        "BACKGROUND_IMAGE" => "-",
        "BASKET_URL" => "/personal/cart/",
        "BRAND_USE" => "N",
        "BROWSER_TITLE" => "-",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "360000",
        "CACHE_TYPE" => "A",
        "CHECK_SECTION_ID_VARIABLE" => "Y",
        "COMPATIBLE_MODE" => "Y",
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUB",
        "DETAIL_PICTURE_MODE" => array("POPUP","MAGNIFIER"),
        "DETAIL_URL" => "/amp/catalog/#ELEMENT_CODE#/",
        "DISABLE_INIT_JS_IN_COMPONENT" => "Y",
        "DISPLAY_COMPARE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PREVIEW_TEXT_MODE" => "S",
        "ELEMENT_CODE" => $_REQUEST["ELEMENT_CODE"],
        "ELEMENT_ID" => $_REQUEST["ELEMENT_ID"],
        "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_MESS_BTN_BUY" => "Выбрать",
        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
        "GIFTS_SHOW_IMAGE" => "Y",
        "GIFTS_SHOW_NAME" => "Y",
        "GIFTS_SHOW_OLD_PRICE" => "Y",
        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "IBLOCK_ID" => "11",
        "IBLOCK_TYPE" => "catalog",
        "IMAGE_RESOLUTION" => "16by9",
        "LABEL_PROP" => array(),
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "LINK_IBLOCK_ID" => "",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_PROPERTY_SID" => "",
        "MAIN_BLOCK_PROPERTY_CODE" => array(),
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "Купить",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_COMMENTS_TAB" => "Комментарии",
        "MESS_DESCRIPTION_TAB" => "Описание",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "MESS_PRICE_RANGES_TITLE" => "Цены",
        "MESS_PROPERTIES_TAB" => "Характеристики",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_LIMIT" => "0",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array("Розничная"),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
        "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
        "PRODUCT_PROPERTIES" => array(),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_SUBSCRIPTION" => "Y",
        "PROPERTY_CODE" => array(
            0 => "ARTNUMBER",
            1 => "COM_BLACK",
            2 => "NEWPRODUCT",
            3 => "MANUFACTURER_DETAIL",
            4 => "MATERIAL",
            5 => "SEO_TEXT",
            6 => "LINKED_ELEMETS",
            7 => "COUNTRY",
            9 => "COLOR",
            10 => "DIAMETR",
            11 => "VNESHNIY_DIAMETR",
            12 => "VNUNTRENNIY_DIAMETR",
            13 => "VISOTA",
            14 => "DLINNA",
            15 => "TYPE_OF_PROFILE",
            16 => "SHIRINA",
            17 => "KOLICHESTVO_ZUBEV",
            18 => "POWER",
            19 => "TYPE_OF_MOUNT",
            20 => "PLACE_OF_CONTACTS",
            21 => "POWER",
            22 => "NUMBER_OF_CONTACTS",
            23 => "VOLUME",
            24 => "COVERING",
            25 => "RESISTANCE",
            26 => "HOLE",
            27 => "FEATURES",
            28 => "TYPE_OF_BORE",
            29 => "ANGLE",
            30 => "WARRANTY",
            31 => "TYPE_OF_BELT",
            32 => "MATERIAL",
            33 => "KOMPLEKT",
            34 => "VNUTRENNIY_KVADRAT",
            35 => "OBSHIY_RAZMER",
            36 => "ORIGINALS_CODES"
        ),
        "SECTION_CODE" => "",
        "SECTION_CODE_PATH" => "",
        "SECTION_ID" => $_REQUEST["SECTION_ID"],
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_URL" => "/amp/sections/#SECTION_CODE#/",
        "SEF_MODE" => "Y",
        "SEF_RULE" => "/amp/catalog/#ELEMENT_CODE#/",
        "SET_BROWSER_TITLE" => "Y",
        "SET_CANONICAL_URL" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "Y",
        "SET_VIEWED_IN_COMPONENT" => "N",
        "SHOW_404" => "N",
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DEACTIVATED" => "N",
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_MAX_QUANTITY" => "N",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_SLIDER" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "TEMPLATE_THEME" => "blue",
        "USE_COMMENTS" => "N",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_GIFTS_DETAIL" => "N",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N",
        "USE_RATIO_IN_RANGES" => "N",
        "USE_VOTE_RATING" => "Y",
        "VOTE_DISPLAY_AS_RATING" => "vote_avg"
    )
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>