<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
?><?
$APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "ampmodel",
    array(
        "COMPONENT_TEMPLATE" => "model",
        "IBLOCK_TYPE" => "catalog",
        "IBLOCK_ID" => "17",
        "ELEMENT_ID" => "",
        "ELEMENT_CODE" => $_REQUEST["ELEMENT_CODE"],
        "CHECK_DATES" => "Y",
        "FIELD_CODE" => array(
            0 => "ID",
            1 => "CODE",
            2 => "XML_ID",
            3 => "NAME",
            4 => "PREVIEW_TEXT",
            5 => "PREVIEW_PICTURE",
            6 => "",
        ),
        "PROPERTY_CODE" => array(
            0 => "model_name",
            1 => "model",
            2 => "model_new",
            3 => "manufacturer",
            4 => "type_of_product",
            5 => "SIMPLEREPLACE_PRODUCTS",
            6 => "instruction",
            7 => "model_new_link",
            8 => "INDCODE",
            9 => "VIEW",
            10=> "POSITION",
            11=> "COMCODE",
            12=> "RESTORE_PRODUCTS",
            13=> "VERSION",
			14=> "SIMPLEREPLACE_VIEW",
            15=> "SIMPLEREPLACE_POSITION",
            16=> "SIMPLEREPLACE_COMCODE",
			17=> "SIMPLEREPLACE_INDCODE"
        ),
        "IBLOCK_URL" => "",
        "DETAIL_URL" => "",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "360000000",
        "CACHE_GROUPS" => "Y",
        "SET_TITLE" => "Y",
        "SET_CANONICAL_URL" => "N",
        "SET_BROWSER_TITLE" => "Y",
        "BROWSER_TITLE" => "-",
        "SET_META_KEYWORDS" => "Y",
        "META_KEYWORDS" => "-",
        "SET_META_DESCRIPTION" => "Y",
        "META_DESCRIPTION" => "-",
        "SET_LAST_MODIFIED" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "ADD_SECTIONS_CHAIN" => "N",
        "ADD_ELEMENT_CHAIN" => "Y",
        "ACTIVE_DATE_FORMAT" => "d.m.Y",
        "USE_PERMISSIONS" => "N",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "USE_SHARE" => "N",
        "PAGER_TEMPLATE" => ".default",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "PAGER_TITLE" => "Страница",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "SET_STATUS_404" => "Y",
        "SHOW_404" => "N",
        "MESSAGE_404" => "Аксессуары и запасные части по Вашему запросу отсутствуют. Перейдите в список моделей или воспользуйтесь поиском.",
        "DEFAULT_TITLE" => "Аксессуары и запасные части для %s"
    ),
    false
);?>
<?$APPLICATION->IncludeComponent(
    "impel:meta",
    "",
    Array(
        "AREA_ID" => "",
        "BLOCK_COLUMNS" => "",
        "BLOCK_TITLE" => "",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",

    )
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>