<?
$arSortByItem = [
	542 => [
		'WARRANTY', 'MATERIAL', 'VISOTA',
	],
	543 => [
		'WARRANTY', 'MATERIAL', 'VISOTA',
	],
	545 => [
		'VISOTA', 'WARRANTY', 'MATERIAL', 
	],
];
$arSortByCategory = [
    //Хлебопечки
	28 => [
	'TYPEPRODUCT', 'TYPE_OF_BELT', 'TYPE_OF_FABRIC', 'TIP_STAKANA', 'VOLUME', 'POWER', 'VOLTAGE', 'AMPERAGE', 'CAPACITANCE', 'temp', 'DLINNA', 'DLINA_VALA', 'VNESHNIY_DIAMETR', 'DIAMETR', 'VNUNTRENNIY_DIAMETR', 'VISOTA', 'SHIRINA', 'TOLSHCINA', 'VYSOT_POSADKI', 'RAZMER_POSADKI', 'DIAMETR_POSADKI', 'KOLICHESTVO_ZUBEV', 'FORMA', 'MATERIAL', 'COVERING', 'COLOR', 'KOMPLEKT', 'WARRANTY', 'MANUFACTURER_DETAIL', 'COUNTRY',
	],
	//Блендеры
	40 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'KOLICHESTVO_ZUBEV','MANUFACTURER_DETAIL', 'COUNTRY',
	],
    //Кух.комбайны
	1585 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'OBSHIY_RAZMER', 'KOLICHESTVO_ZUBEV','MANUFACTURER_DETAIL', 'COUNTRY',
	],
	//Мясорубки
	27 => [
		'OBSHIY_RAZMER','VNUTRENNIY_KVADRAT','TOLSHCINA','VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'VISOTA', 'DLINNA', 'SHIRINA', 'KOLICHESTVO_ZUBEV','MANUFACTURER_DETAIL', 'COUNTRY',
	],
	//Стиралки
    66 => [
		'VNUNTRENNIY_DIAMETR', 'VNESHNIY_DIAMETR', 'DIAMETR', 'VISOTA', 'DLINNA', 'TYPE_OF_PROFILE', 'SHIRINA','RASSTOYANIE_KREPEJA', 'DIAMETR_VTULKI', 'RESISTANCE',  'POWER', 'TYPE_OF_MOUNT', 'CONNECT', 'PLACE_OF_CONTACTS', 'KOLICHESTVO_ZUBEV','DIAMETR_POD_PODShIPNIK', 'DIAMETR_VTULKI_POD_SALNIK','RASSTOJaNIE','DLINA_VALA', 'MANUFACTURER_DETAIL', 'COUNTRY',
	],
		//Холодильники
    96 => [
		'DLINNA', 'RASSTOYANIE_KREPEJA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'COKOL', 'POWER','MANUFACTURER_DETAIL', 'COUNTRY',
	],
    //Блендеры
	1587 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'KOLICHESTVO_ZUBEV','MANUFACTURER_DETAIL', 'COUNTRY',
	],
    //Мультиварки
    45 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'KOLICHESTVO_ZUBEV', 'VOLUME','MANUFACTURER_DETAIL', 'COUNTRY',
	],
     //СВЧ
     29 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'KOLICHESTVO_ZUBEV', 'VOLUME','MANUFACTURER_DETAIL', 'COUNTRY',
	],
    //Пылесос
    24 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'DIAMETR', 'KOLICHESTVO_ZUBEV', 'VOLUME','MANUFACTURER_DETAIL', 'COUNTRY',
	],
    //Для варочных панелей
    110 => [
        'TYPEPRODUCT', 'TIP_STOLA', 'TIP_RASSEKATELJA', 'DLINNA', 'VNESHNIY_DIAMETR', 'DIAMETR', 'VNUNTRENNIY_DIAMETR', 'VISOTA', 'SHIRINA', 'TOLSHCINA', 'VYSOT_POSADKI', 'RAZMER_POSADKI', 'DIAMETR_POSADKI', 'MATERIAL', 'COLOR', 'KOMPLEKT', 'WARRANTY', 'MANUFACTURER_DETAIL', 'COUNTRY',	],
	//Для духовых шкафов
    913 => [
		'DLINNA', 'VISOTA', 'SHIRINA', 'VNESHNIY_DIAMETR', 'VNUNTRENNIY_DIAMETR', 'COKOL', 'POWER','MAX_TEMP','DIAMETR', 'KOLICHESTVO_ZUBEV', 'VOLUME','MANUFACTURER_DETAIL', 'COUNTRY',
	],
];